# Generated by Django 3.1.5 on 2021-03-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'дом', 'verbose_name_plural': 'дома'},
        ),
    ]
