# Generated by Django 4.0 on 2024-02-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_house_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-active', 'name'], 'verbose_name': 'дом', 'verbose_name_plural': 'дома'},
        ),
    ]
